Exercise #1

In [4]:
try:
    N = int(input('Enter positive integer number N: '))
    if N <= 0 or N >= 10**25:
        raise ValueError
    
    sum = 0
    
    for i in range(N+1):
        sum += i
    print(f'Summary result: {sum}')
    
except ValueError:
    print('Please, input correct positive number less than 10^25')

Enter positive integer number N: 3
Summary result: 6


Exercise #2(Counting islands)
1. Get valid data

In [11]:
import numpy as np
try:
    M = int(input('Number of rows: M = '))
    N = int(input('Number of columns: N = '))
    if M <= 0 or N <= 0:
        raise ValueError('Array dimensions are incorrect')
    
    data_matrix = []
    print('Enter rows elements')
    for i in range(1, M+1):
        row = [int(i) for i in input(f'Row №{i}: ').split()]
        if len(row) != N:
            raise ValueError('Incorrect count of elements in a row')
        elif row.count(1)+row.count(0) != N:
            raise ValueError('Only 0 and 1 are available')
        data_matrix.append(row)
    
    matrix = np.array(data_matrix)
    print(f'Result matrix: \n{matrix}')

except ValueError as e:
    print(e)

Number of rows: M = 4
Number of columns: N = 4
Enter rows elements
Row №1: 1 0 0 0
Row №2: 1 0 1 0
Row №3: 0 1 1 1
Row №4: 1 0 0 1
Result matrix: 
[[1 0 0 0]
 [1 0 1 0]
 [0 1 1 1]
 [1 0 0 1]]


2. Get islands count

In [12]:
if matrix.any():
    
    def find_full_island(i, j):
        islands_matrix[i][j] = count + 1
        if i != 0 and islands_matrix[i-1][j] == 1:
            find_full_island(i-1,j)
        if i != M-1 and islands_matrix[i+1][j] == 1:
            find_full_island(i+1, j)
        if j != 0 and islands_matrix[i][j-1] == 1:
            find_full_island(i, j-1)
        if j != N-1 and islands_matrix[i][j+1] == 1:
            find_full_island(i, j+1)
        
    islands_matrix = np.array(matrix) 
    count = 0
    for i in range(M):
        for j in range(N):
            if islands_matrix[i][j] == 1:
                count += 1
                find_full_island(i,j)

    print(f'Number of islands: {islands_matrix.max()-1}')
    print(islands_matrix)
else:
    print('There are zero islands')

Number of islands: 3
[[2 0 0 0]
 [2 0 3 0]
 [0 3 3 3]
 [4 0 0 3]]
